image: node:18.18.0

stages:
  - lint
  - test

lint-client:
  stage: lint 
  script:
    - npm intall
    - cd client && npm run lint
  allow_failure: true

  
lint-server:
  stage: lint 
  script:
    - npm intall
    - cd server && npm run lint
  allow_failure: true

server-test:
  stage: test
  script:
    - cd server
    - npm install
    - npm run test
