image: node:18.18.0

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - lint
  - test

cache:
    key:
      files:
        - ./server/package.json
    paths:
      - .cache/server
    key:
      files:
        - ./client/package.json
    paths:
      - .cache/client


lint-client:
  stage: lint 
  script:
    - cd client
    - npm install
    - npm ci --cache .cache/client
    - npm run lint
  allow_failure: false

  
lint-server:
  stage: lint 
  script:
    - cd client
    - npm install eslint
    - npm run lint
    - npm install
    - npm ci --cache .cache/client
  allow_failure: false

server-test:
  stage: test
  script:
    - cd server
    - npm ci --cache .cache/server
    - npm run test
  allow_failure: false

client-build:
  stage: test
  script:
    - cd client
    - npm ci --cache .cache/client
    - npm run build
  allow_failure: false
